/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { MembershipPlugin } from "./MembershipPlugin";
export type { MembershipPluginSetup } from "./MembershipPluginSetup";
