/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as dao from "./dao";
export * as permission from "./permission";
export * as plugin from "./plugin";
