/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMembershipPlugin } from "./IMembershipPlugin";
export type { IPluginRepository } from "./IPluginRepository";
