/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IPluginRepository {
  export type VersionStruct = {
    pluginSetup: PromiseOrValue<string>;
    buildMetadata: PromiseOrValue<BytesLike>;
  };

  export type VersionStructOutput = [string, string] & {
    pluginSetup: string;
    buildMetadata: string;
  };
}

export interface IPluginRepositoryInterface extends utils.Interface {
  functions: {
    "createVersion(bytes32,address,bytes)": FunctionFragment;
    "latestVersion(bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "createVersion" | "latestVersion"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createVersion",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "latestVersion",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(
    functionFragment: "createVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestVersion",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IPluginRepository extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPluginRepositoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createVersion(
      _name: PromiseOrValue<BytesLike>,
      _pluginSetup: PromiseOrValue<string>,
      _buildMetadata: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    latestVersion(
      _name: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[IPluginRepository.VersionStructOutput]>;
  };

  createVersion(
    _name: PromiseOrValue<BytesLike>,
    _pluginSetup: PromiseOrValue<string>,
    _buildMetadata: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  latestVersion(
    _name: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<IPluginRepository.VersionStructOutput>;

  callStatic: {
    createVersion(
      _name: PromiseOrValue<BytesLike>,
      _pluginSetup: PromiseOrValue<string>,
      _buildMetadata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    latestVersion(
      _name: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<IPluginRepository.VersionStructOutput>;
  };

  filters: {};

  estimateGas: {
    createVersion(
      _name: PromiseOrValue<BytesLike>,
      _pluginSetup: PromiseOrValue<string>,
      _buildMetadata: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    latestVersion(
      _name: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createVersion(
      _name: PromiseOrValue<BytesLike>,
      _pluginSetup: PromiseOrValue<string>,
      _buildMetadata: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    latestVersion(
      _name: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
