/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as daoAuthorizable from "./dao-authorizable";
export type { daoAuthorizable };
export type { IPlugin } from "./IPlugin";
export type { PluginUUPSUpgradeable } from "./PluginUUPSUpgradeable";
