/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  PermissionLib,
  PermissionLibInterface,
} from "../../../../../@aragon/osx/core/permission/PermissionLib";

const _abi = [
  {
    inputs: [],
    name: "NO_CONDITION",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6091610038600b82828239805160001a607314602b57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80636dd02a5b146038575b600080fd5b603f600081565b6040516001600160a01b03909116815260200160405180910390f3fea264697066735822122067484b8728f8defdd9f156ce86a7569317192b8fad49184a459bed331c9810da64736f6c63430008130033";

type PermissionLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PermissionLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PermissionLib__factory extends ContractFactory {
  constructor(...args: PermissionLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<PermissionLib> {
    return super.deploy(overrides || {}) as Promise<PermissionLib>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): PermissionLib {
    return super.attach(address) as PermissionLib;
  }
  override connect(signer: Signer): PermissionLib__factory {
    return super.connect(signer) as PermissionLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PermissionLibInterface {
    return new utils.Interface(_abi) as PermissionLibInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PermissionLib {
    return new Contract(address, _abi, signerOrProvider) as PermissionLib;
  }
}
